steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/project-11c88d7b-34b1-4178-af8/cloud-run-source-deploy/auticare/auti-care:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
images:
  - 'europe-west1-docker.pkg.dev/project-11c88d7b-34b1-4178-af8/cloud-run-source-deploy/auticare/auti-care:latest'
options:
  logging: CLOUD_LOGGING_ONLY
